backend:
  name: github
  repo: xxxkjing/astro-blog-thought-lite
  branch: main # Branch to update (optional; defaults to master)

# i18n
i18n:
  structure: multiple_folders
  locales: [zh-cn]
  default_locale: zh-cn

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "jotting"
    label: "随笔"
    folder: "src/content/jotting/zh-cn"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布时间", name: "timestamp", widget: "datetime" }
      - { label: "系列", name: "series", widget: "string", required: false }
      - { label: "标签", name: "tags", widget: "list", required: false }
      - { label: "描述", name: "description", widget: "text", required: false }
      - { label: "正文", name: "body", widget: "markdown" }
  - name: "note"
    label: "笔记"
    folder: "src/content/note/zh-cn"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布时间", name: "timestamp", widget: "datetime" }
      - { label: "标签", name: "tags", widget: "list", required: false }
      - { label: "描述", name: "description", widget: "text", required: false }
      - { label: "正文", name: "body", widget: "markdown" }
  - name: "preface"
    label: "序言"
    folder: "src/content/preface/zh-cn"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{second}}"
    identifier_field: "timestamp"
    fields:
      - { label: "发布时间", name: "timestamp", widget: "datetime" }
      - { label: "正文", name: "body", widget: "markdown" }
  - name: "information"
    label: "信息"
    files:
      - label: "关于我"
        name: "introduction"
        file: "src/content/information/zh-cn/introduction.md"
        fields:
          - { label: "正文", name: "body", widget: "markdown" }
      - label: "隐私政策"
        name: "policy"
        file: "src/content/information/zh-cn/policy.md"
        fields:
          - { label: "正文", name: "body", widget: "markdown" }
      - label: "鸣谢"
        name: "roll"
        file: "src/content/information/zh-cn/roll.md"
        fields:
          - { label: "正文", name: "body", widget: "markdown" }