backend:
  name: github
  repo: xxxkjing/astro-blog-thought-lite # TODO: Replace with your repo name
  branch: main

i18n:
  structure: multiple_folders
  locales: [zh-cn, en]
  default_locale: zh-cn

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "note"
    label: "文记"
    folder: "src/content/note/{{locale}}"
    create: true
    i18n: true
    slug: "{{slug}}" # This will use the title to generate the filename slug
    fields:
      - { label: "标题", name: "title", widget: "string", i18n: true }
      - { label: "发布日期", name: "timestamp", widget: "datetime" }
      - { label: "系列", name: "series", widget: "string", required: false, i18n: true }
      - { label: "标签", name: "tags", widget: "list", required: false, i18n: true }
      - { label: "描述", name: "description", widget: "text", required: false, i18n: true }
      - { label: "敏感内容", name: "sensitive", widget: "boolean", default: false, required: false }
      - { label: "显示目录", name: "toc", widget: "boolean", default: false, required: false }
      - { label: "置顶权重", name: "top", widget: "number", default: 0, required: false, value_type: "int", min: 0 }
      - { label: "草稿", name: "draft", widget: "boolean", default: false, required: false }
      - { label: "正文", name: "body", widget: "markdown", i18n: true }
  - name: "jotting"
    label: "随笔"
    folder: "src/content/jotting/{{locale}}"
    create: true
    i18n: true
    slug: "{{slug}}"
    fields:
      - { label: "标题", name: "title", widget: "string", i18n: true }
      - { label: "发布日期", name: "timestamp", widget: "datetime" }
      - { label: "标签", name: "tags", widget: "list", required: false, i18n: true }
      - { label: "描述", name: "description", widget: "text", required: false, i18n: true }
      - { label: "敏感内容", name: "sensitive", widget: "boolean", default: false, required: false }
      - { label: "置顶权重", name: "top", widget: "number", default: 0, required: false, value_type: "int", min: 0 }
      - { label: "草稿", name: "draft", widget: "boolean", default: false, required: false }
      - { label: "正文", name: "body", widget: "markdown", i18n: true }
  - name: "preface"
    label: "序文"
    folder: "src/content/preface/{{locale}}"
    create: true
    i18n: true
    slug: "{{timestamp}}"
    identifier_field: "timestamp"
    fields:
      - { label: "发布日期", name: "timestamp", widget: "datetime", format: "YYYY-MM-DD-HH-mm-ss", date_format: "YYYY-MM-DD", time_format: "HH-mm-ss" }
      - { label: "正文", name: "body", widget: "markdown", i18n: true }
  - name: "information"
    label: "信息"
    files:
      - name: "introduction"
        label: "介绍"
        file: "src/content/information/{{locale}}/introduction.md"
        fields:
          - { label: "正文", name: "body", widget: "markdown" }
      - name: "policy"
        label: "政策"
        file: "src/content/information/{{locale}}/policy.md"
        fields:
          - { label: "正文", name: "body", widget: "markdown" }
      - name: "roll"
        label: "滚动"
        file: "src/content/information/{{locale}}/roll.md"
        fields:
          - { label: "正文", name: "body", widget: "markdown" }
      - name: "chronicle"
        label: "纪事"
        file: "src/content/information/{{locale}}/chronicle.yaml"
        fields:
          - name: "entries"
            label: "纪事条目"
            widget: "list"
            fields:
              - { label: "日期", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
              - { label: "更新内容", name: "updates", widget: "list" }